const BASE_URL = "http://testlab.imecar.com:8082"; // replace with your API base URL

export const Endpoints = {
  ROOT: `${BASE_URL}`,
  LOGIN: `${BASE_URL}/login/`,
  USER: `${BASE_URL}/user/`,
  USERME: `${BASE_URL}/user/me/`,
  SOURCE: `${BASE_URL}/source/`,
  TENANT: `${BASE_URL}/tenant/`,
  COMPANY: `${BASE_URL}/company/`,
  PERMISSION: `${BASE_URL}/permission/`,
  MODULE: `${BASE_URL}/module/`,
  ROLE: `${BASE_URL}/role/`,
  DEPARTMENT: `${BASE_URL}/department/`,
  USERDETAIL: `${BASE_URL}/userDetail/`,
  CALENDAR: `${BASE_URL}/calendar/`,
  SOCIALFLOW: `${BASE_URL}/socialFlow/`,
  SOCIALFLOWTYPE: `${BASE_URL}/socialFlowType/`,
  FORM: `${BASE_URL}/form/`,
  SCOREDETAIL: `${BASE_URL}/scoreDetail/`,
  FORMTYPE: `${BASE_URL}/form_type/`,
  DEBITVOUCHER: `${BASE_URL}/debit_voucher/`,
  DEBITREQUEST: `${BASE_URL}/debit_request/`,
  CALENDARTYPE: `${BASE_URL}/calendarType/`,
  RAPOR: `${BASE_URL}/rapor/`,
  DEBITDASHBOARD: `${BASE_URL}/debitdashboard/`,
  IMAGEUPLOAD: `https://mj.imecar.com/uploads/uf.php`,
};
